### ISSUE TITLE
The pretrained models on VOC.

### ISSUE THREAD

**Issue by LiWentomng** [NVlabs/DiscoBox#11]
Hello, thanks for your promising work!  Is it convenient to share the pretrained models for the Pascal VOC? 
Thank you in advance.

**Comment by voidrank** [comment]
Hi @LiWentomng ,

Check this folder https://drive.google.com/drive/folders/1LCWVpGvDOwgNcAJowsLBJ9E656iT0aVv.

Best,

Shiyi

**Comment by LiWentomng** [comment]
Thanks!
Best,
Wentong
