### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Huster-Hq** [NVlabs/DiscoBox#13]
ImportError: /home/user/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK3c1010TensorImpl36is_contiguous_nondefault_policy_implENS_12MemoryFormatE

**Comment by voidrank** [comment]
Hi @Huster-Hq 

This is probably caused by misaligned versions of mmcv and mmdet. Please re-install mmcv and mmdet.
