### ISSUE TITLE
Why the mask_gt still in the code?

### ISSUE THREAD

**Issue by BlueCat7** [NVlabs/DiscoBox#2]
In the disco_solo_head the input of loss has a maks_gt_list, and it is used in the code. It is may our my fault understanding. Thanks for the good work.

**Comment by voidrank** [comment]
Hi @BlueCat7 ,
mask_gt_list is replaced by box_mask, see https://github.com/NVlabs/DiscoBox/blob/main/mmdet/datasets/pipelines/loading.py#L460
