### ISSUE TITLE
Question about the BoxInst Mentioned in the paper

### ISSUE THREAD

**Issue by lh-zhu** [NVlabs/DiscoBox#3]
Greetings! Thanks for supporting your code for your awesome work!

I noticed that you have listed the result of BoxInst in your paper, would you have try to re-implement BoxInst in your mmdet code?

**Comment by voidrank** [comment]
Hi @Unrealluver 

Thanks for your interest in our work!

No, we didn't implement BoxInst in mmdet.

**Comment by lh-zhu** [comment]
Thank you for your reply!
