### ISSUE TITLE
Results of model with 1x r50 on COCO.

### ISSUE THREAD

**Issue by LiWentomng** [NVlabs/DiscoBox#4]
Hello, thanks for your promising work.
Due to the long training time of 3x  on COCO, can you provide the AP resutls of COCO with 1x training schedule  as a performance reference.

**Comment by voidrank** [comment]
Hi @LiWentomng 

Thanks for your interest in our work. I'm not very sure about the exact mAP of DiscoBox(1x/ResNet-50), but I believe it was around 29.0 mAP on COCO val2017.

Best,

Shiyi

**Comment by LiWentomng** [comment]
Thanks for your reply, got it.
